# This is mostly just a convenience to start common tasks from the root directory
version: "3"

silent: true

dotenv: [".env"]

includes:
  contracts: ./taskfile/contracts.yml
  components: ./taskfile/components.yml
  backend: ./taskfile/backend.yml
  deploy: ./taskfile/deploy.yml
  test: ./taskfile/test.yml
  telegram: ./taskfile/telegram.yml

tasks:
  default:
    cmds:
      - task --list-all

  clean:
    desc: "Clean all artifacts"
    cmds:
      - echo "Cleaning artifacts in {{.ARTIFACTS_PATH}}"
      - rm -rf "{{.ARTIFACTS_PATH}}"

  lint:
    desc: "Run code formatting and linting checks"
    cmds:
      - cargo fmt --all -- --check
      - cargo fix --allow-dirty --allow-staged
      - cargo clippy --all-targets -- -D warnings

  docker-pull:
    desc: "Pull required Docker images"
    cmds:
      - |
        {{.DOCKER_SUDO}} docker pull {{.COSMWASM_OPTIMIZER_IMAGE}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.WAVS_DOCKER_IMAGE}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.WAVS_CW_MIDDLEWARE_DOCKER_IMAGE}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.JAEGER_DOCKER_IMAGE}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.PROMETHEUS_DOCKER_IMAGE}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.IPFS_DOCKER_IMAGE}}

  build-all:
    desc: "Build everything that needs building"
    cmds:
      - task components:build-all
      - task contracts:build-all
      - task contracts:schema-all

  debugging:
    cmds:
      - task components:build-all
      - task contracts:build-all
      - task deploy:operator-delete-service
      # - task deploy:all SKIP_UPLOAD_CONTRACTS=true
      - task deploy:all
