# This is mostly just a convenience to start common tasks from the root directory
version: "3"

silent: true

dotenv: [".env"]

includes:
  contracts: ./taskfile/contracts.yml
  components: ./taskfile/components.yml
  backend: ./taskfile/backend.yml
  deploy: ./taskfile/deploy.yml
  test: ./taskfile/test.yml

tasks:
  default:
    cmds:
      - task --list-all

  clean:
    desc: "Clean all artifacts"
    cmds:
      - rm -rf "{{.ARTIFCACTS_PATH}}"

  lint:
    desc: "Run code formatting and linting checks"
    cmds:
      - cargo fmt --all -- --check
      - cargo fix --allow-dirty --allow-staged
      - cargo clippy --all-targets -- -D warnings
