/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
// @ts-nocheck

import * as _0 from "./TgContractPayments.types";
import * as _1 from "./TgContractPayments.client";
import * as _2 from "./TgContractPayments.message-composer";
import * as _3 from "./baseClient";
export namespace contracts {
  export const TgContractPayments = {
    ..._0,
    ..._1,
    ..._2
  };
  export const baseClient = {
    ..._3
  };
}