/* eslint-disable @typescript-eslint/no-empty-object-type */
/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Auth =
  | {
      service_manager: string;
    }
  | {
      admin: string;
    };
export interface InstantiateMsg {
  allowed_denoms: string[];
  auth: Auth;
}
export type ExecuteMsg =
  | {
      register_receive: RegisterReceiveMsg;
    }
  | {
      send_payment: SendPaymentMsg;
    }
  | {
      register_send: {
        tg_handle: string;
      };
    }
  | {
      wavs: ServiceHandlerExecuteMessages;
    };
export type Uint256 = string;
export type ServiceHandlerExecuteMessages = {
  wavs_handle_signed_envelope: {
    envelope: WavsEnvelope;
    signature_data: WavsSignatureData;
  };
};
export type WavsEnvelope = Binary;
export type Binary = string;
export type HexBinary = string;
export type EvmAddr = string;
export interface RegisterReceiveMsg {
  chain_addr: string;
  tg_handle: string;
}
export interface SendPaymentMsg {
  amount: Uint256;
  denom: string;
  from_tg: string;
  to_tg: string;
}
export interface WavsSignatureData {
  reference_block: number;
  signatures: HexBinary[];
  signers: EvmAddr[];
}
export type QueryMsg =
  | {
      addr_by_tg: {
        handle: string;
      };
    }
  | {
      tg_by_addr: {
        account: string;
      };
    }
  | {
      admin: {};
    }
  | {
      pending_payments: {
        handle: string;
      };
    }
  | {
      allowed_denoms: {};
    }
  | {
      wavs: ServiceHandlerQueryMessages;
    };
export type ServiceHandlerQueryMessages = {
  wavs_service_manager: {};
};
export interface ChainAddrResponse {
  addr?: string | null;
}
export interface AdminResponse {
  admin?: string | null;
}
export type ArrayOfString = string[];
export type ArrayOfCoin = Coin[];
export interface Coin {
  amount: Uint256;
  denom: string;
}
export interface TgHandleResponse {
  handle?: string | null;
}
export type Null = null;
