[package]
name = "tg-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
tg-contract-api = { workspace = true }
tg-utils = { workspace = true, features = ["binary"] }
wavs-types = { workspace = true }
layer-climb = { workspace = true}
axum = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
rustls = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
dotenvy = {workspace = true}
thiserror = {workspace = true}
reqwest = {workspace = true}
cosmwasm-std = {workspace = true}
