[package]
name = "tg-component-aggregator-messenger"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
tg-utils = { workspace = true, features = ["wasi"] }
tg-contract-api = { workspace = true }
tg-components-shared = { workspace = true }
layer-climb = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
wstd = { workspace = true }
wavs-wasi-utils = { workspace = true }
wit-bindgen-rt = { workspace = true }
thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
wavs-types = {workspace = true}
wit-bindgen = {workspace = true}
serde_json = {workspace = true}

[lib]
crate-type = ["cdylib"]
