[default]
log_level = ["debug"]

# Those configs are global and shared between wavs and aggregator
jaeger = "http://localhost:4317"
prometheus = "http://localhost:9090"


# ----------------------------
# Chain configurations
# ----------------------------

# Neutron testnet: https://github.com/cosmos/chain-registry/blob/master/testnets/neutrontestnet/chain.json
# This must match the config in `backend/chains`
[default.chains.cosmos.pion-1]
bech32_prefix = "neutron"
rpc_endpoint = "http://localhost:26657"
grpc_endpoint = "http://localhost:9090"
gas_price = 0.025
gas_denom = "untrn"

# ----------------------------
# WAVS specific settings
# ----------------------------
[wavs]
cors_allowed_origins = [
    "https://lay3rlabs.github.io/*",
    "http://localhost:*",
    "http://127.0.0.1:*",
]


# ----------------------------
# CLI specific settings
# ----------------------------
[cli]
# The directory to store the data.
data = "~/wavs/cli"


# ----------------------------
# Aggregator specific settings
# ----------------------------
[aggregator]
# The directory to store the data.
data = "~/wavs/aggregator"

cors_allowed_origins = [
    "https://lay3rlabs.github.io/*",
    "http://localhost:*",
    "http://127.0.0.1:*",
]
