[package]
name = "tg-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
full = ["multitest", "client-pool", "client", "telegram", "dep:tokio", "dep:toml", "reqwest"]
multitest = ["dep:cw-multi-test"]
client-pool = ["dep:deadpool"]
client = []
telegram = []
reqwest = ["dep:reqwest"]

[dependencies]
tg-contract-api = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
cosmwasm-std = { workspace = true }
layer-climb = { workspace = true }
tracing = {workspace = true}
cfg-if = {workspace = true}
tracing-subscriber = {workspace = true}
anyhow = {workspace = true}
wavs-types = {workspace = true}
thiserror = {workspace = true}
async-trait = {workspace = true}
toml = {workspace = true, optional = true}
reqwest = {workspace = true, optional = true}
tokio = {workspace = true, optional = true}
deadpool = { workspace = true, optional = true }
cw-multi-test = { workspace = true, optional = true }
